### ISSUE TITLE
Use Sentinel error for invalid HMAC

### ISSUE THREAD

**Issue by freb** [Xeoncross/go-aesctr-with-hmac#1]
It would be nice to return a specific error type for the case in decryption where the HMAC is invalid. (https://github.com/Xeoncross/go-aesctr-with-hmac/blob/master/crypt.go#L146). It seems you have two main error categories when doing decryption, something went wrong, and the HMAC didn't match. It would be nice to easily tell if it was the latter.

Instead of returning an `errors.New`, you could return a previously declared: `var ErrInvalidHMAC = errors.New("Invalid HMAC")`

**Comment by xeoncross** [comment]
Do you mean you want new error types? 

```
type ErrInvalidHMAC struct {}

func (e *ErrInvalidHMAC) Error() string {
    return "Invalid HMAC"
}
```

Usage

```
if !hmac.Equal(mac, h.Sum(nil)) {
	return &ErrInvalidHMAC{}
}
```

**Comment by freb** [comment]
Either a new error type as you showed, or just a new instances of an error (I've seen them called sentinel errors). One example of an error instance is the sql.ErrNoRows error:

https://github.com/golang/go/blob/master/src/database/sql/sql.go#L331

With a type, you have to do a type assertion to check the error:

```go
type ErrInvalidHMAC struct {}
//...

err := aesctr.Decrypt(...)
e, ok := err.(ErrInvalidHMAC)
if ok {
// now we know its invalid hmac
}
```

With an error instance, you just have to do a simple comparison:
```go
var ErrInvalidHMAC = errors.New("Invalid HMAC")
//...

err := aesctr.Decrypt(...)
if err == ErrInvalidHMAC {
// now we know its invalid hmac
}
```

You've may have seen this, but Dave Cheney has some thoughts on the different approaches: <https://dave.cheney.net/2016/04/27/dont-just-check-errors-handle-them-gracefully>.

It doesn't matter to me which you use. Either will allow me to check the error without having to do a string comparison.

**Comment by xeoncross** [comment]
Good idea. Done: https://github.com/Xeoncross/go-aesctr-with-hmac/commit/f61976125796a84fc85e46df91744fc609b9cdf7

**Comment by freb** [comment]
Awesome, Thanks!
