### ISSUE TITLE
Use with http

### ISSUE THREAD

**Issue by nicolaspernoud** [Xeoncross/go-aesctr-with-hmac#2]
Hello,

I am trying to use your library to encrypt over golang webdav.
I came up with a middleware that doesn't work (PUT requests do not end), but GET requests seems OK.

```go
// Encrypt enables body encryption (to be use with PUT requests)
func Encrypt(next http.Handler, key []byte) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		pipeReader, pipeWriter := io.Pipe()
		go aesctr.Encrypt(r.Body, pipeWriter, key, key)
		r.Body = ioutil.NopCloser(pipeReader)
		next.ServeHTTP(w, r)
	})
}

// Decrypt enables body decryption (to be use with GET requests)
func Decrypt(next http.Handler, key []byte) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		wdecrypt := &decryptWriter{
			writer: w,
			key:    key,
		}
		next.ServeHTTP(wdecrypt, r)
	})
}

type decryptWriter struct {
	writer http.ResponseWriter
	key    []byte
}

func (r *decryptWriter) Header() http.Header {
	return r.writer.Header()
}

func (r *decryptWriter) Write(p []byte) (int, error) {
	reader := bytes.NewReader(p)
	err := aesctr.Decrypt(reader, r.writer, r.key, r.key)
	return len(p), err
}

func (r *decryptWriter) WriteHeader(status int) {
	r.writer.WriteHeader(status)
}
```

Would you have any idea how to make this work ?
Minio/SIO has an EncryptReader method which would be easier to use on the request body, but has the webdav implementation works with 32kb chunks, it doesn't work for me (or I missed something).

Thanks,

Best regards.

**Comment by xeoncross** [comment]
Hey @nicolaspernoud I added a sample [http handler test](https://github.com/Xeoncross/go-aesctr-with-hmac/blob/master/http_test.go) you can look at that might give you some ideas. Unfortunately, it's not producing the correct result and I didn't implement the decrypt yet to see what the issue is. I don't have time today to fix it, but wanted to push something up for you to look at.

Also, the `decryptWriter.Write` won't work because it's calling decrypt for every unique chunk written which means it won't have the full chunk (nor the hmac).

**Comment by nicolaspernoud** [comment]
Hello,

Thanks a lot for your answer. I still do not understand why the encrypt is not working... But I undertstood why the decrypt didn't with your explanation.

For now I switched to minio/sio with the encrypt writers and readers that seems a bit easier for my particular use case. It appears that wasn't the webdav chunking which caused problems, but me forgetting to close the stream. I will therefore close the issue, but I would still be interested in knowing how to use your library in an http case.

Best regards.
